### ISSUE TITLE
Inventory / Hosts - wrong representation

### ISSUE THREAD

**Issue by tux1980** [ansible-cloud/aws_demos#29]
Hi,

I did recreate that in my own env (AAP2.3 on my Openshift) without any bigger problems unless one issue what is annoying. 
In the official lab, you see, after executing the playbook/template "Create AWS Instances" the two created rhel notes marked as "rhel1" and "rhel2" in the AAP Dynamic inventory.
In my own AAP2 inventory I see the Public IPv4 DNS Name like "ec2-3-71-23-94.eu-central-1.compute.amazonaws.com" 
![inventory](https://user-images.githubusercontent.com/46625474/220628743-a5f85f03-7132-4cf8-8da8-ef382ed280f2.png)

Any Idea what that might cause?

Thanks
Wolfgang

**Comment by HichamMourad** [comment]
Hi Wolfgang.

If the inventory source configuration has the following then you will see them listed by their name.

        source_vars:
          private: "false"
          hostnames:
            - 'tag:Name'
          compose: 
            ansible_host: public_ip_address

Thanks.

**Comment by HichamMourad** [comment]
Issue resolved.

![image](https://user-images.githubusercontent.com/43329991/220662290-7b41bfb4-e19c-44c5-ac3d-bdd7e2f4aa95.png)
